### ISSUE TITLE
compile error on cento7.2

### ISSUE THREAD

**Issue by worker24h** [Kurento/bugtracker#594]
## Prerequisites

These are MANDATORY, otherwise the issue will be automatically closed.

* [] I agree to fill this issue template.
* [] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description
I'm building kms-core:6.16.0 on centos7.2, but it's occurs a problem.

[ 78%] Building CXX object src/server/CMakeFiles/kmscoreimpl.dir/implementation/EventHandler.cpp.o
In file included from /root/kurento/kms-core/src/server/implementation/EventHandler.cpp:19:0:
/root/kurento/kms-core/src/server/implementation/WorkerPool.hpp:42:3: 
error: expected constructor, destructor, or type conversion before ‘post’
   post (BOOST_ASIO_MOVE_ARG (CompletionHandler) handler)
   ^
/root/kurento/kms-core/src/server/implementation/EventHandler.cpp: In function ‘void kurento::post_task(std::function<void()>)’:
/root/kurento/kms-core/src/server/implementation/EventHandler.cpp:30:11: 
error: ‘class kurento::WorkerPool’ has no member named ‘post’
   workers.post (cb);
           ^
make[2]: *** [src/server/CMakeFiles/kmscoreimpl.dir/implementation/EventHandler.cpp.o] Error 1
make[1]: *** [src/server/CMakeFiles/kmscoreimpl.dir/all] Error 2
make: *** [all] Error 2
[root@63d5c0084f5b build]#

### About Kurento Media Server

* Kurento version:  
* Server OS:          
* Installation method:
    
  - [] [apt-get]
  - [] [Docker]
  - [] [AWS CloudFormation]
  - [] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### About your Application Server

* Programming Language:  
* Kurento Client version:     

### About end-user clients

* Device(s):    
* OS(es):        
* Browser(s):  

### Run these commands

```
cat /etc/lsb-release
```

```
kurento-media-server --version
```

```
dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by worker24h** [comment]
Please help me, thanks

**Comment by j1elo** [comment]
Try adding `#include <boost/asio/async_result.hpp>` as the first include in kms-core/src/server/implementation/WorkerPool.hpp

It should look like this:
```
#include <boost/asio/async_result.hpp>
#include <boost/asio/io_service.hpp>
#include <boost/asio/steady_timer.hpp>
#include <boost/thread/thread.hpp>
```

Does this solve the compilation error at this file?

**Comment by worker24h** [comment]
> Try adding `#include <boost/asio/async_result.hpp>` as the first include in kms-core/src/server/implementation/WorkerPool.hpp
> 
> It should look like this:
> 
> ```
> #include <boost/asio/async_result.hpp>
> #include <boost/asio/io_service.hpp>
> #include <boost/asio/steady_timer.hpp>
> #include <boost/thread/thread.hpp>
> ```
> 
> Does this solve the compilation error at this file?

**Upgrade boost version to 1.65.0**.

I solve it.

**Comment by j1elo** [comment]
> **Upgrade boost version to 1.65.0**.
> 
> I solve it.

Nice!
Kurento compiles fine on Ubuntu 16.04 with Boost 1.58.0. But 1.65 works fine, too.
