### ISSUE TITLE
Can't build with glibc 2.34

### ISSUE THREAD

**Issue by davispuh** [Kurento/bugtracker#629]
## Prerequisites

* [x] I agree to fill this issue template.
* [x] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

```
server/death_handler.cpp: In static member function ‘static void Debug::DeathHandler::SignalHandler(int, void*, void*)’:
server/death_handler.cpp:591:52: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘MallocHook’?
591 |   void * (*oldMallocHook) (size_t, const void *) = __malloc_hook;
|                                                    ^~~~~~~~~~~~~
|                                                    MallocHook
server/death_handler.cpp:592:48: error: ‘__free_hook’ was not declared in this scope
592 |   void (*oldFreeHook) (void *, const void *) = __free_hook;
|                                                ^~~~~~~~~~~
```

Deprecated malloc hooks are not present in glibc 2.34.

## Context

malloc hooks (`__malloc_hook`, `__free_hook`) have been deprecated for many years and now they have been removed.

## How to reproduce?

Build against glibc 2.34+

## Expected & current behavior

Expected to build and not error.

### About Kurento Media Server

* Kurento version:  6.17
* Server OS:          Arch Linux
* Installation method:
  - [x] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### Run these commands

```
$ cat /etc/lsb-release
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
```

**Comment by j1elo** [comment]
Note that Kurento 6.x is only expected to compile on Ubuntu 16.04 and 18.04, so this is not a bug.

Nonetheless, I'd like to help building on other systems if the required changes are simple. In this case, it is possible that the issue was already solved on the pre-release brach for Kurento 7.0, so we could try that...

Could you please replace `kurento-media-server/server/death_handler.cpp` and `kurento-media-server/server/death_handler.hpp` with the corresponding files from https://github.com/vmarkovtsev/DeathHandler/tree/43486a96db24233fe6148b5b992b5242de8608db

If that works, I'll bring those two files in for the upcoming release 6.18.

**Comment by davispuh** [comment]
It's just matter of time till other distributions will use newer glibc :P and I just did that and it built successfully.

**Comment by j1elo** [comment]
This is fixed for upcoming Kurento 7.0 which works on top of Ubuntu 20.04
